### ISSUE TITLE
Display a list of guides on /guides

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/teamwilder#60]
## User story

As a person looking for guidance or inspiration I need to be able to see what content the site has so that I can find or discover useful information.

## Acceptance criteria

- [ ] I can see an alphabetical list of guides
- [ ] I can search for guides and actions with free text

## Implementation notes & questions
- Do we want people to be able to browse case studies or only see them as related to guides?
- Do we in the first instance just present a list of resource teaser and a list of case studies on the page that is `/stories` and `/guides`? @katjam not keen on this - but it is simple & maybe expected behaviour.

**Comment by katjam** [comment]
@undividual this is a conversation starter for what we do with listings for resources and case studies.

**Comment by undividual** [comment]
RE "Do we want people to be able to browse case studies or only see them as related to guides?" — I think ultimately we definitely want people to be able to browse them but as part of this initial prototype (and poss what we release in July) they are just linked from guides. The reason for this is because I think this is where mapping could likely come in later (i.e. these high quality case studies/stories being naviagable by location) and we agreed not to do this initially.

I'm not sure I understand the second bit about teasers so may need to discuss when I speak to @katjam on Tue

**Comment by r-ferrier** [comment]
verified: 
![Screenshot 2023-05-29 at 17 13 54](https://github.com/geeksforsocialchange/teamwilder/assets/46496391/ae82c31e-7723-4824-9c52-26235032cff7)
