### ISSUE TITLE
[Bug]: Edits to existing pages no longer updating

### ISSUE THREAD

**Issue by AutumnBarlow** [geeksforsocialchange/teamwilder#609]
At 3.30 yesterday afternoon I added a video to Types of Community Group but this has not shown up on the website either for me or others (therefore not a cookie issue on my computer). I made another tweak to see if this would push it through but nothing. I have made other small edits to other pages later yesterday afternoon, in the text of the pages to see if it was just a video issue - while the edits show in the CMS they are still not showing on the live site.

(I often find that I have to hit save a few times as it often reverts immediately to "unsaved changes" in the CMS and then sometimes goes completely blank.)

**Comment by katjam** [comment]
@autumn, this may be due to time it takes to save the changes because it has to push them to github. When you press save there's a very thin progress bar line that runs along the top. Are you waiting fo that to finish?

Otherwise there might be an issue with the build I'll check on that and also add a badge to the github so you can see if the build is failing.

**Comment by katjam** [comment]
Build is failing. I'll check why.
![image](https://github.com/geeksforsocialchange/teamwilder/assets/861172/63fa5d56-653a-4ac2-957f-8cfb0cfba6c3)

**Comment by katjam** [comment]
I think it's to do with some files I added for the production SEO.

**Comment by katjam** [comment]
Fixed.
